QUESTION_TEMPLATE = [
    "Are both lung fields clear, with no evidence of infiltrates or consolidations?",
    "Are there signs of atelectasis or lung segment collapse?",
    "Do you observe any nodules or masses suggestinglung tumors?",
    "Are there signs of pulmonary edema, such as Kerley B lines?",
    "Is the lung vasculature normal?",
    "Do you see any evidence of interstitial lung disease or honeycombing?",
    "Are there any signs of airspace disease consistent with pneumonia?",
    "Are there signs of pulmonary fibrosis or pleural plaques?",
    "Are there any abnormalities in the lung apices, ruling out tuberculosis?",
    "Are there any signs of bronchiectasis?",
    "Is the lung volume normal,suggesting hyperinflation/collapse?",
    "Can you find any sign of pulmonary metastases?",
    "Are there any signs of miliary nodules?",
    "Are there any signs of vascular enlargement, suggesting pulmonary hypertension?",
    "Do you note lung cysts or bullae?",
    "Can you rule out any signs of pulmonary fibrosis, such as reticular opacities or honeycombing?",
    "is there air trapping, suggestive of obstructive lung disease?",
     "Is there vascular compression or displacement by mediastinal masses?",
    'Are the heart borders well-defined, without signs of pericardial effusion?', 
    'Is the cardiac shape normal?', 
    'are there cardiac calcifications or valve calcifications?', 
   'Are there widened mediastinal structures?', 
   'Are there any signs of heart failure, such as pulmonary edema or pleural effusion?', 
  'Are there any signs of constrictive pericarditis?', 
  'Can you confirm the absence of aortic dissection or intramural hematoma?', 
    'Are there any signs of cardiac masses or tumors?',
    'Are there any signs of pericardial calcifications or constrictive pericarditis?',
    'Are there any signs of cardiac shunts, electronic devices, tubes or central venous catheter?',
    "Are there any signs of rib fractures or callus formation suggesting healing fractures?",
    "Can you confirm the absence of any signs of scoliosis or other vertebral abnormalities?",
    "Can you confirm the absence of soft tissue hematomas, masses, lipomas or swelling?",
    "Are there any signs of scapular or clavicular abnormalities?",
    "Are there any signs of sternoclavicular joint dislocation or arthritis?",
    "Is there acromioclavicular joint separation?",
    "Are there any problems with the shoulder joints?",
    "Are there any signs of vertebral abnormalities?",
    "Are there calcified lymph nodes?",
    "Are there any problems in this xray image?",
    "what is/are the size of the mass if it is present?",
    "where is the location of the pleural effusion if it is present?",
    "How big is the pleural effusion if present?"
    "where is the location of the consolidation if it is present?",
    "if there is a mass in the immage, where is its location?",
    "what is/are the size of the nodule if you note any?",
    "whats wrong in the image?",
    "what are the notable findings in this radiograph?",
    "what are the problems that can be noted in this image?",
    "What is the most likely diagnosis  given this image?",
    "What are the differential diagnosis for this image?",  
    "Are there tracheobronchial foreign bodies or aspirated material?",
    "Are there signs of pulmonary fibrosis, such as reticular opacities or honeycombing?",
    "Are there signs of air trapping, suggestive of obstructive lung disease?",
    "Can you confirm the absence of aortic abnormalities?",
    "Are there any signs of aortic aneurysm or aortic dissection/calcification?",
    "Are there any signs of congestion or pleural effusion due to heart failure?",
    "is there pleural effusion or pleural thickening?",
    "Are there any signs of pneumothorax or pneumomediastinum?",
    "Are there any signs of pleural calcifications or pleural plaques?",
    "Are the lung apices free of any pulmonary nodules, pleural-based abnormalities or pleural-based lesions?",
    "Are there any signs of subpulmonic effusion or loculated pleural collections?",
    "Are there any signs of pleural- based infiltrates, empyema or abscess formation?",
    "Are there any signs of pleural-based infections, such as pleural empyema or pleural abscess?",
    "Are there any signs of pleural-based infiltrates?",
    "Are there any signs of pleural-based metastases or pleural nodules?",
    "Is there pleural fibrosis or pleural calcifications?",
    "Are there any signs of pleural-based pneumothorax or pneumomediastinum?",
    "Are there signs of tuberculosis or granuloma?",
    "Is the trachea in the midline position, ruling out tracheal deviation?",
    "Are there any signs of thymic enlargement or thymoma in the anterior mediastinum?",
   "Is there diaphragmatic rupture/diaphragmatic eventration?",
  "Are there any signs of diaphragmatic hernias, such as hiatal hernia?",
  ]


# others = {
  
#   "Mediastinum": [
#     "Can you confirm the absence of any esophageal abnormalities, such as strictures or diverticula?",
#     "Are the major vessels, including the aorta, superior vena cava, and brachiocephalic veins, normal in appearance?",
#     "Can you rule out any signs of aortic arch anomalies, such as a double aortic arch or vascular rings?",
#     "Are the lymph nodes within the mediastinum of normal size and shape, without signs of lymphadenopathy?",
#     "Can you confirm the absence of mediastinal cysts or mediastinal lipomatosis?",
#     "Are there any signs of mediastinal neurogenic tumors, such as neurofibroma or schwannoma?",
#     "Are there any signs of mediastinal teratoma or other germ cell tumors?",
#     "Can you rule out any signs of mediastinal lymphoma or thymic hyperplasia?",
#     "Are there any signs of mediastinal hematoma or aortic aneurysm?",
#     "Is the trachea in the midline position, ruling out tracheal deviation?",
#     "Are there any signs of tracheal or bronchial foreign bodies?",
#     "Can you confirm the absence of tracheal or bronchial stenosis?",
#     "Are there any signs of tracheoesophageal fistula or bronchoesophageal fistula?",
#     "Are there any signs of tracheobronchial tumors or tracheomalacia?",
#     "Can you rule out any signs of esophageal masses or diverticula?",
#     "Are there any signs of esophageal strictures or varices?",
#     "Are there any signs of vascular compression or displacement by mediastinal masses?",
#     "Can you confirm the absence of pericardial effusion or pericardial thickening?",
#     "Are there any signs of pericardial calcifications or pericardial cysts?",
#     "Can you confirm the absence of mediastinal cysts or mediastinal lipomatosis?",
#     "Are there any signs of mediastinal neurogenic tumors, such as neurofibroma or schwannoma?",
#     "Are there any signs of mediastinal teratoma or other germ cell tumors?",
#     "Can you rule out any signs of mediastinal lymphoma or thymic hyperplasia?",
#     "Are there any signs of mediastinal hematoma or aortic aneurysm?",
#     "Is the trachea in the midline position, ruling out tracheal deviation?",
#     "Are there any signs of tracheal or bronchial foreign bodies?",
#     "Can you confirm the absence of tracheal or bronchial stenosis?",
#     "Are there any signs of tracheoesophageal fistula or bronchoesophageal fistula?",
#     "Are there any signs of tracheobronchial tumors or tracheomalacia?",
#     "Can you rule out any signs of esophageal masses or diverticula?",
#     "Are there any signs of esophageal strictures or varices?",],
#   "Esophagus": [
#     "Can you rule out any signs of esophageal masses or diverticula?",
#     "Are there any signs of esophageal wall thickening or esophagitis?",
#     "Can you confirm the absence of esophageal perforation or esophageal rupture?",
#     "Are there any signs of esophageal tumors, such as squamous cell carcinoma or adenocarcinoma?",
#     "Are there any signs of esophageal foreign bodies or impacted food bolus?",
#     "Can you rule out any signs of esophageal motility disorders, such as achalasia or diffuse esophageal spasm?",
#     "Are there any signs of esophageal dilatation or esophageal diverticula?",
#     "Are there any signs of esophageal varices or esophageal webs?",
#     "Can you confirm the absence of esophageal dysmotility or gastroesophageal reflux disease?",
#     "Are there any signs of esophageal fistulas, such as tracheoesophageal or bronchoesophageal fistula?",
#     "Are there any signs of vascular compression due to esophageal anomalies or aortic arch anomalies?",
#     "Can you rule out any signs of esophageal tumors, such as leiomyoma or leiomyosarcoma?",
#     "Are there any signs of esophageal diverticula or Zenker's diverticulum?",
#     "Are there any signs of esophageal ring or Schatzki ring?",
#     "Can you confirm the absence of esophageal strictures or esophageal spasm?",
#     "Are there any signs of pleural-based sarcoidosis or pleural-based hemangioma?",
#     "Are there any signs of pleural-based hydatid cyst or pleural-based lung herniation?",
#     "Can you rule out any signs of pleural-based hematoma or pleural-based infarction?",
#     "Are there any signs of pleural-based lymphoma or pleural-based metastases?",
#     "Are there any signs of pleural-based endometriosis or pleural-based fibroma?",
#     "Can you confirm the absence of pleural-based granulomatosis or pleural-based necrosis?"],
  
#   "Diaphragm": [
#     
#     "Are there any signs of diaphragmatic tumors, such as leiomyoma or lipoma?",
#     "Can you rule out any signs of diaphragmatic lymphadenopathy or metastases?",
#     "Are both hemidiaphragms moving symmetrically during respiration?",
#     "Are there any signs of phrenic nerve injury or paralysis?",    
#     "Can you confirm the absence of diaphragmatic eventration or diaphragmatic thinning?",
#     "Are there any signs of diaphragmatic paralysis on fluoroscopy?",
#     "Can you rule out any signs of Morgagni hernia or Bochdalek hernia?",
#     "Are there any signs of diaphragmatic rupture or diaphragmatic tear?",
#     "Is the diaphragm adequately positioned without any signs of upward or downward displacement?",
#     "Are there any signs of diaphragmatic lymphangioma or diaphragmatic lipoma?",
#     "Can you rule out any signs of diaphragmatic metastases or diaphragmatic abscess?",
#     "Are both hemidiaphragms moving symmetrically during respiration?",
#     "Are there any signs of phrenic nerve injury or phrenic nerve palsy?",
#     "Can you confirm the absence of eventration or diaphragmatic thinning?",
#     "Are there any signs of diaphragmatic hernias, such as hiatal hernia or Morgagni hernia?",
#     "Are there any signs of diaphragmatic rupture or diaphragmatic tear?",
#     "Can you rule out any signs of diaphragmatic hematoma or diaphragmatic infarction?",
#     "Are there any signs of diaphragmatic tumors, such as leiomyoma or liposarcoma?",
#     "Are there any signs of diaphragmatic inflammation, such as diaphragmatic pleurisy?",
#     "Can you confirm the absence of diaphragmatic eventration or diaphragmatic agenesis?",
#     "Are both hemidiaphragms smoothly outlined without any signs of diaphragmatic irregularities?",
#     "Are there any signs of diaphragmatic amyloidosis or diaphragmatic myopathy?",
#     "Can you rule out any signs of diaphragmatic muscle tear or diaphragmatic strain?",
#     "Are there any signs of diaphragmatic fibrosis or diaphragmatic granuloma?",
#     "Are there any signs of diaphragmatic necrosis or diaphragmatic edema?",
#     "Can you confirm the absence of diaphragmatic hydatid cyst or diaphragmatic empyema?",
#     "Are both hemidiaphragms intact, ruling out diaphragmatic eventration or diaphragmatic elevation?",
#     "Are there any signs of diaphragmatic calcification or diaphragmatic perforation?",
#     "Can you rule out any signs of diaphragmatic hematoma or diaphragmatic injury?"
#   ],
# }


 

